# Partition info
BOARD_BOOTIMAGE_PARTITION_SIZE := 32768
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 38912
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 3145728
BOARD_USERDATAIMAGE_PARTITION_SIZE := 57339904
BOARD_CACHEIMAGE_PARTITION_SIZE := 204800
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE  := ext4
BOARD_FLASH_BLOCK_SIZE := 4096

# Use this flag if the board has a ext4 partition larger than 2gb
BOARD_HAS_LARGE_FILESYSTEM := true
TARGET_USERIMAGES_USE_EXT4 := true
#TARGET_USERIMAGES_USE_F2FS := true
#BOARD_SUPPRESS_SECURE_ERASE := true
